src/packaged/main/objects/PdfTemplate__c/PdfTemplate__c.object-meta.xml
<CustomObject>
    <description>Stores config information about PDF Templates that are used to render Quotes, Invoices, Orders, etc</description>
    <label>PDF Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/main/objects/PdfTemplate__c/fields/AddressFormatting__c.field-meta.xml
<CustomField>
    <fullName>AddressFormatting__c</fullName>
    <description>Custom formatting for the recipient address. Allows to inject custom HTML code and placeholder</description>
    <inlineHelpText>Enter the formatting that is used to display the recipient address. You can enter any raw text, placeholders in the format {!FieldName}, i.e. {!BillingStreet}, for merge fields and line breaks.</inlineHelpText>
    <label>Address Formatting</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

src/packaged/main/objects/PdfTemplate__c/fields/DateFormatting__c.field-meta.xml
<CustomField>
    <fullName>DateFormatting__c</fullName>
    <defaultValue>&quot;dd.MM.yyyy&quot;</defaultValue>
    <description>Formatter pattern that is used to format all date values on the quote.</description>
    <inlineHelpText>Enter the pattern that will be used to format dates. See https://mobilityhouse.atlassian.net/wiki/spaces/PI/pages/1503461403/Configure+Pattern+to+Format+Date+Values+on+PDFs for more details.</inlineHelpText>
    <label>Date Formatting</label>
    <type>Text</type>
    <length>30</length>
</CustomField>

src/packaged/main/objects/PdfTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description for this PDF Template. Used as help text to guide users where this template may be used.</description>
    <inlineHelpText>Enter the template&#39;s description</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/packaged/main/objects/PdfTemplate__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checking &quot;Is Active&quot; makes the template available for users when the PDF Template can be selected</description>
    <inlineHelpText>Active to display the template to Users</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/main/objects/PdfTemplate__c/fields/LetterFormat__c.field-meta.xml
<CustomField>
    <fullName>LetterFormat__c</fullName>
    <description>Letter Format CSS that is used to render the PDF</description>
    <inlineHelpText>Select the letter format for the rendered PDF</inlineHelpText>
    <label>Letter Format</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIN_5008_Type_A</fullName>
                <default>true</default>
                <label>DIN 5008 (Type A)</label>
            </value>
            <value>
                <fullName>ANSI_Letter</fullName>
                <label>ANSI Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/objects/PdfTemplate__c/fields/TaxDisplayOptions__c.field-meta.xml
<CustomField>
    <fullName>TaxDisplayOptions__c</fullName>
    <description>Different options how tax column (per line item) and tax totals should be displayed</description>
    <inlineHelpText>Select the display options for taxes on this PDF</inlineHelpText>
    <label>Tax Display Options</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Show_Column_Show_NetGross_Prices</fullName>
                <default>true</default>
                <label>Show Column, Show Net and Gross Prices</label>
            </value>
            <value>
                <fullName>Show_Column_Show_Net_Prices</fullName>
                <label>Show Column, Show Net Prices Only</label>
            </value>
            <value>
                <fullName>Show_Column_Show_Gross_Prices</fullName>
                <label>Show Column, Show Gross Prices Only</label>
            </value>
            <value>
                <fullName>Hide_Column_Show_NetGross_Prices</fullName>
                <label>Hide Column, Show Net and Gross Prices</label>
            </value>
            <value>
                <fullName>Hide_Column_Show_Net_Prices</fullName>
                <label>Hide Column, Show Net Prices Only</label>
            </value>
            <value>
                <fullName>Hide_Column_Show_Gross_Prices</fullName>
                <label>Hide Column, Show Gross Prices Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/classes/DemoAddressController.cls
public class DemoAddressController {

    public static final String PARAM_TEMPLATE_ID = 'templateId';
    public static final String PARAM_RECORD_ID = 'id';

    public static PdfTemplate__c Template {
        public get {
            if (Template == null && TemplateId != null) {
                Template = [SELECT Id,AddressFormatting__c,DateFormatting__c,Description__c,IsActive__c,LetterFormat__c,TaxDisplayOptions__c FROM PdfTemplate__c WHERE Id = :TemplateId];
            }
            return Template;
        }
        private set;
    }

    public static Quote QuoteRecord {
        public get {
            if (QuoteRecord == null) {
                QuoteRecord = [SELECT Id,CreatedDate,BillingStreet,BillingPostalCode,BillingCity,BillingCountryCode,BillingStateCode FROM Quote WHERE Id = :RecordId];
            }
            return QuoteRecord;
        }
        private set;
    }

    public static String TemplateId {
        public get {
            if (String.isNotBlank(ApexPages.currentPage().getParameters().get(PARAM_TEMPLATE_ID))) {
                TemplateId = ApexPages.currentPage().getParameters().get(PARAM_TEMPLATE_ID);
            }
            return TemplateId;
        }
        private set;
    }

    public static String RecordId {
        public get {
            if (String.isNotBlank(ApexPages.currentPage().getParameters().get(PARAM_RECORD_ID))) {
                RecordId = ApexPages.currentPage().getParameters().get(PARAM_RECORD_ID);
            }
            return RecordId;
        }
        private set;
    }

    public static Component.Apex.PageBlock DynamicAddress {
        public get {
            if (DynamicAddress == null && Template != null && String.isNotBlank(Template.AddressFormatting__c)) {
                DynamicAddress dynAddr = new DynamicAddress(Template.AddressFormatting__c);
                dynAddr.RecordVariableName = 'QuoteRecord';
                DynamicAddress = dynAddr.getAddressAsPageBlock();
            }
            return DynamicAddress;
        }
        private set;
    }

    public static String DateFormatting {
        public get {
            if (DateFormatting == null) {
                if (String.isNotBlank(Template.DateFormatting__c)) {
                    DateFormatting = '{0, date, '+ Template.DateFormatting__c +'}';
                } else {
                    DateFormatting = '{0, date, dd.MM.yyyy}';
                }
            }
            return DateFormatting;
        }
        private set;
    }

}